In [99]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [63]:
df = pd.read_csv(r'C:\Users\Saksham Gupta\Desktop\Udemy\Part 1 - Data Preprocessing\Data.csv')

In [107]:
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [108]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [109]:
print(x,y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [110]:
imputer = Imputer(missing_values = 'NaN' , strategy = "mean", axis=0)

C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [111]:
imputer = imputer.fit(x[:,1:3])

In [112]:
x[:,1:3] = imputer.transform(x[:,1:3]).shape

In [113]:
print(x)

[['France' 10 2]
 ['Spain' 10 2]
 ['Germany' 10 2]
 ['Spain' 10 2]
 ['Germany' 10 2]
 ['France' 10 2]
 ['Spain' 10 2]
 ['France' 10 2]
 ['Germany' 10 2]
 ['France' 10 2]]


In [114]:
labelencoder = LabelEncoder()

In [115]:
x[:,0] = labelencoder.fit_transform(x[:,0])

In [116]:
print(x[:,0])

[0 2 1 2 1 0 2 0 1 0]


In [85]:
onehotencoder = OneHotEncoder(categorical_features = [0])
#index you want to one hot encode comes in categorical feature

In [86]:
x = onehotencoder.fit_transform(x).toarray()

C:\Program Files\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Program Files\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [87]:
x

array([[ 1.,  0.,  0., 10.,  2.],
       [ 0.,  0.,  1., 10.,  2.],
       [ 0.,  1.,  0., 10.,  2.],
       [ 0.,  0.,  1., 10.,  2.],
       [ 0.,  1.,  0., 10.,  2.],
       [ 1.,  0.,  0., 10.,  2.],
       [ 0.,  0.,  1., 10.,  2.],
       [ 1.,  0.,  0., 10.,  2.],
       [ 0.,  1.,  0., 10.,  2.],
       [ 1.,  0.,  0., 10.,  2.]])

In [88]:
labelencoder = LabelEncoder()

In [89]:
y = labelencoder.fit_transform(y)

In [90]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [98]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [100]:
std = StandardScaler()

In [101]:
x_train = std.fit_transform(x_train)
x_test = std.fit(x_test)
#test me split nahi kia..!!

In [102]:
#do we need to fit and transform dummy variables...!!....person to person dependent